# Prometheus configuration for unified_orchestrator monitoring

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'unified_orchestrator'
    environment: 'production'

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - 'alertmanager:9093'

# Load alert rules
rule_files:
  - 'alerts.yml'

# Scrape configurations
scrape_configs:
  # Unified Orchestrator metrics
  - job_name: 'unified_orchestrator'
    static_configs:
      - targets: ['host.docker.internal:9090']
        labels:
          service: 'orchestrator'
    
  # MLflow metrics
  - job_name: 'mlflow'
    static_configs:
      - targets: ['mlflow:5000']
        labels:
          service: 'mlflow'
    metrics_path: '/metrics'
    
  # Node exporter (system metrics)
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
        labels:
          service: 'system'

